
build:
  version: 2.0.1
account:
  message: "Welcome to eazybank QA account API"
  contactDetails:
    name: "Annukriti Joshi"
    email: "annu08joshi@gmail.com"
  onCallSupport:
    - 05610-08101
    - 05410-00110
