
build:
  version: 1.0.0
account:
  message: "Welcome to eazybank account API"
  contactDetails:
    name: "Ashutosh Joshi"
    email: "ashu98.joshi@gmail.com"
  onCallSupport:
    - 00110-08101
    - 08010-00110
